-- Active: 1740996226560@@localhost@5433@dnd_db
--CREATE DATABASE IF NOT EXISTS dnd_db;
DROP SCHEMA IF EXISTS "public" CASCADE;
CREATE SCHEMA IF NOT EXISTS "public";

-- ----------------------------------------- Enums -----------------------------------------
DROP TYPE IF EXISTS "character_state_enum";
CREATE TYPE "character_state_enum" AS ENUM (
  'In combat',
  'Resting',
  'Died'
);

DROP TYPE IF EXISTS "action_type_enum";
CREATE TYPE "action_type_enum" AS ENUM (
  'cast spell',
  'collect item',
  'item drop',
  'pass round',
  'continue',
  'round start',
  'round end',
  'combat end',
  'combat start',
  'death',
  'rest',
  'join'
);

DROP TYPE IF EXISTS "effect_type_enum";
CREATE TYPE "effect_type_enum" AS ENUM (
  'damage',
  'healing',
  'vamp'
);
-- ----------------------------------------- Attributes -----------------------------------------
DROP TABLE IF EXISTS "Attributes";
CREATE TABLE "Attributes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL UNIQUE,
  "description" text NOT NULL
);

-- ----------------------------------------- Classes -----------------------------------------
DROP TABLE IF EXISTS "Classes";
CREATE TABLE "Classes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL UNIQUE,
  "description" text,
  "ap_modifier" DECIMAL(3, 2) NOT NULL,
  "inventory_modifier" DECIMAL(3, 2) NOT NULL,
  "ac_modifier" DECIMAL(3, 2) NOT NULL
);

DROP TABLE IF EXISTS "ClassAttributes";
CREATE TABLE "ClassAttributes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" bigint NOT NULL,
  "attribute_id" bigint NOT NULL,
  "modifier" DECIMAL(3, 2) NOT NULL,
  FOREIGN KEY ("class_id") REFERENCES "Classes" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("attribute_id") REFERENCES "Attributes" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------- Items -----------------------------------------
DROP TABLE IF EXISTS "Items";
CREATE TABLE "Items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text NOT NULL,
  "weight" int NOT NULL
);

DROP TABLE IF EXISTS "ItemAttributes";
CREATE TABLE "ItemAttributes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item_id" bigint NOT NULL,
  "attribute_id" bigint NOT NULL,
  "modifier" int NOT NULL,
  FOREIGN KEY ("item_id") REFERENCES "Items" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("attribute_id") REFERENCES "Attributes" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------- Combats -----------------------------------------
DROP TABLE IF EXISTS "Combats";
CREATE TABLE "Combats" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "act_round_number" int NOT NULL,
  "time_started" TIMESTAMP NOT NULL,
  "time_ended" TIMESTAMP
);

DROP TABLE IF EXISTS "CombatRounds";
CREATE TABLE "CombatRounds" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "combat_id" bigint NOT NULL,
  "time_started" TIMESTAMP NOT NULL,
  "time_ended" TIMESTAMP,
  "round_number" int NOT NULL,
  FOREIGN KEY ("combat_id") REFERENCES "Combats" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS "CombatItems";
CREATE TABLE "CombatItems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "combat_id" bigint NOT NULL,
  "item_id" bigint NOT NULL,
  FOREIGN KEY ("combat_id") REFERENCES "Combats" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("item_id") REFERENCES "Items" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------- Characters -----------------------------------------
DROP TABLE IF EXISTS "Characters";
CREATE TABLE "Characters" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" bigint NOT NULL,
  "state" "character_state_enum" NOT NULL,
  "experience_points" int NOT NULL,
  FOREIGN KEY ("class_id") REFERENCES "Classes" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS "CharacterAttributes";
CREATE TABLE "CharacterAttributes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" bigint NOT NULL,
  "attribute_id" bigint NOT NULL,
  "base_value" int NOT NULL,
  FOREIGN KEY ("character_id") REFERENCES "Characters" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("attribute_id") REFERENCES "Attributes" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS "Inventory";
CREATE TABLE "Inventory" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" bigint NOT NULL,
  "item_id" bigint NOT NULL,
  FOREIGN KEY ("character_id") REFERENCES "Characters" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("item_id") REFERENCES "Items" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS "CombatParticipants";
CREATE TABLE "CombatParticipants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" bigint NOT NULL,
  "combat_id" bigint NOT NULL,
  "act_health" int NOT NULL,
  "act_action_points" int NOT NULL,
  "round_passed" BOOLEAN NOT NULL,
  FOREIGN KEY ("character_id") REFERENCES "Characters" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("combat_id") REFERENCES "Combats" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------- Spells -----------------------------------------
DROP TABLE IF EXISTS "SpellCategories";
CREATE TABLE "SpellCategories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL UNIQUE,
  "description" text NOT NULL,
  "base_cost" int NOT NULL
);

DROP TABLE IF EXISTS "Spells";
CREATE TABLE "Spells" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL UNIQUE,
  "description" text NOT NULL,
  "category_id" bigint NOT NULL,
  "base_effect" int NOT NULL,
  "effect_type" effect_type_enum NOT NULL,
  FOREIGN KEY ("category_id") REFERENCES "SpellCategories" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS "CharacterSpells";
CREATE TABLE "CharacterSpells" (
  "character_id" bigint NOT NULL,
  "spell_id" bigint NOT NULL,
  PRIMARY KEY ("character_id", "spell_id"), -- Composite primary key
  FOREIGN KEY ("character_id") REFERENCES "Characters" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("spell_id") REFERENCES "Spells" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS "SpellAttributes";
CREATE TABLE "SpellAttributes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "spell_id" bigint NOT NULL,
  "attribute_id" bigint NOT NULL,
  FOREIGN KEY ("spell_id") REFERENCES "Spells" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("attribute_id") REFERENCES "Attributes" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS "Actions";
CREATE TABLE "Actions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "round_id" bigint NOT NULL,
  "spell_id" bigint,
  "action_type" action_type_enum NOT NULL,
  "actor_id" bigint,
  "target_id" bigint,
  "item_id" bigint,
  "ap_cost" int NOT NULL,
  "effect" int NOT NULL,
  "dice_roll" int,
  "action_timestamp" TIMESTAMP,
  FOREIGN KEY ("round_id") REFERENCES "CombatRounds" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("spell_id") REFERENCES "Spells" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("actor_id") REFERENCES "Characters" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("target_id") REFERENCES "Characters" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("item_id") REFERENCES "Items" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- ----------------------------------------- Indexes for Foreign Key Columns -----------------------------------------
CREATE INDEX idx_combatparticipants_combat_id ON "CombatParticipants" ("combat_id");

CREATE INDEX idx_inventory_character_id ON "Inventory" ("character_id");
CREATE INDEX idx_combatitems_combat_id ON "CombatItems" ("combat_id");


CREATE INDEX idx_classattributes_class_id ON "ClassAttributes" ("class_id");
CREATE INDEX idx_characterattributes_character_id ON "CharacterAttributes" ("character_id");

CREATE INDEX idx_spellattributes_spell_id ON "SpellAttributes" ("spell_id");

CREATE INDEX idx_itemattributes_attribute_id ON "ItemAttributes" ("attribute_id");

CREATE INDEX idx_combatrounds_combat_id ON "CombatRounds" ("combat_id");

-- ---------------------------------------------------------------------------------------------------------------------------
-- ----------------------------------------- Special Purpose Indexes -----------------------------------------
-- ----------------------------------------- For fast fetching all actions in a round, ordered by time
CREATE INDEX idx_actions_round_id_timestamp ON "Actions" ("round_id", "action_timestamp");

-- ----------------------------------------- For filtering by action type (e.g., cast spell, death)
CREATE INDEX idx_actions_action_type ON "Actions" ("action_type");
